name: release-on-push-to-main
run-name: Release on Push to Main
description: |
  This workflow triggers a release when changes are pushed to the main branch.
  It uses the Release Please action to create a release and deploys the built project to GitHub Pages.
on:
  push:
    branches:
      - main

permissions:
    contents: write
    pull-requests: write
    pages: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - name: Release Please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          release-type: simple
          token: ${{ secrets.RELEASE_PLEASE_TOKEN }}

  deploy:
    needs: release-please
    if: needs.release-please.outputs.release_created == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "21"

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Build
        run: npm run build

      - name: Deploy to GitHub Pages
        run: npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PLEASE_TOKEN }}
